<?php include __DIR__ . '/_orderInformation.phtml';?>

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Your tickets</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <?php foreach($this->purchase->getTickets() as $ticket):?>
                        <?php $url = $this->url(
                                'root/manage',
                                ['purchaseId' => $this->purchase->getPurchaseId(), 'ticketId' => $ticket->getTicketId()]
                        )?>
                        <tr>
                            <td class="col-xs-6">
                                <?=$ticket->getTicketType()->getDisplayName()?>
                            </td>
                            <td class="col-xs-6">
                                <a href="<?= $this->serverUrl() . $url?>">Manage</a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</div>
