<form id="delegate-form" method="POST">
    <?php $this->form->prepare(); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Delegate Information</h3>
        </div>
        <div class="panel-body">
            <?php echo $this->formCollection($this->form->get('delegate')); ?>
        </div>
    </div>
    <div class="row">
        <div class=" col-xs-offset-7 col-xs-2">
            <?php echo $this->formHidden($this->form->get('security')) ?>
            <button class="btn btn-scotphp pull-right">Update Details</button>
        </div>
    </div>

</form>
